### ISSUE TITLE
Calendar Events Not Displaying Correctly with OnPush Change Detection

### ISSUE THREAD

**Issue by Rattenfaenger49** [michelebombardi/angular-calendar-scheduler#99] opened 2024-06-21 15:37 UTC
When I change the ChangeDetectionStrategy to OnPush in my Angular application, everything initially works correctly. However, when navigating the calendar view to another day, week, or month using the following buttons:

    mwlCalendarPreviousView (=> dateOrViewChanged)
    mwlCalendarNextView (=> dateOrViewChanged)
    mwlCalendarToday (=> dateOrViewChanged)

The appointments or events on the calendar do not stretch to take the full width available. Instead, they occupy only half of the width. This issue resolves itself after I click on any part of the calendar, at which point the events correctly stretch to the full width of their respective dates.
![1](https://github.com/michelebombardi/angular-calendar-scheduler/assets/74275764/55066cbc-8f32-4a8f-bba1-445714b11a62)
![2](https://github.com/michelebombardi/angular-calendar-scheduler/assets/74275764/023068f3-096d-4863-8715-27f629d5f6f8)

ChangeDetectionStrategy.Default works fine  with all functions i have used but   an error is thrown by changing the view in case there is an Event in the new CalenderView
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'max-width': '74'. Current value: '153'. Expression location: CalendarSchedulerEventComponent component. Find more at https://angular.io/errors/NG0100

Triggering change detection manually after the view change  throw an Assertion Error
  this.cdr.detectChanges();  => 
  Error: ASSERTION ERROR: Should be run in update mode [Expected=> false == true <=Actual]
  
 How could help me with solving this issue?

**Comment by michelebombardi** [comment] 2024-08-13 13:12
Hi @Rattenfaenger49 , I've take a look to issues you reported.
Unfortunately I was not able to reproduce any of these. Also with ChangeDetectionStrategy.OnPush all seems to works fine.

Could you post here a reproducible demo?

In the meanwhile I close the issue but feel free to reopen it when you have a demo to see the issue.

Thank you for your help!

**Closed by michelebombardi** 2024-08-13 13:12 UTC
